version: "3.3"

services:
  db:
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 4406:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./dbdata:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpdb

  wordpress:
    image: wordpress:5.3.0-php7.3
    restart: always
    volumes:
      - wordpress:/var/www/html
      - ./wp-content/plugins/maker-blocks:/var/www/html/wp-content/plugins/maker-blocks
      - ./wp-content/themes/maker:/var/www/html/wp-content/themes/maker
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_HOME', 'http://localhost:8080' );
        define( 'WP_SITEURL', 'http://localhost:8080' );

  wpcli:
    image: wordpress:cli
    volumes:
      - wordpress:/var/www/html

volumes:
  dbdata:
  wordpress:
